data_root: /home/vjti-comp/Downloads/A Dataset of Aligned RGB and Multispectral UAV Ima(1)/A Dataset of Aligned RGB and Multispectral UAV Ima/WeedyRice-RGBMS-DB
in_channels: 4
height: 960
width: 1280
batch_size: 8
epochs: 75
lr: 0.001
num_workers: 4
ckpt_dir: ./checkpoints
mixed_precision: false
nir_dropout_prob: 0.2
test_on_rgb_only : true
use_ndvi: true  
base_channels: 16                                  
domain_loss_weight: 0.1                           
grl_lambda: 1.0                                   